Refactor and Enhance Codebase (MS Test) (#5)
* Add ReadIpConfigFile unit tests following a code-first approach
* Refactor program structure into Startup.cs for improved organization
* Add test case for JAPI001_GetResource_NotFound_Returns404
* Fix path separator issue for cross-platform compatibility
* Refactor of the test.yml and quality.yml workflows to run on all existing projects in the solution
* Remove windows from test.yml strategy matrix

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -2,20 +2,33 @@ name: Format Check
 
 on: [push, pull_request]
 
-
-
 jobs:
   format-check:
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
 
     strategy:
       matrix:
-        dotnet-version: [ '6.0.x', '7.0.x' ]
+        dotnet-version: ['6.0.x', '7.0.x']
+
     steps:
       - uses: actions/checkout@v4
+
       - name: Setup .NET
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: ${{ matrix.dotnet-version }}
+
       - name: Check Code Formatting
-        run: dotnet format --verify-no-changes
+        run: |
+          for csproj in $(find . -name '*.csproj'); do
+            # Verify code formatting for each project
+            echo -e "Verifying format for project: $csproj"
+            dotnet format "$csproj" --verify-no-changes
+
+            rc=$?
+
+            if [[ $rc != 0 ]]; then
+              echo "Error: Code formatting check failed for project $csproj"
+              exit $rc
+            fi
+          done
